name: Unit Tests

on:
  pull_request: {}
  push: {}
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: '1.24.0'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          go mod download
      - name: Run Unit Tests
        run: |
          go test -covermode=count -coverprofile=profile.cov ./pkg/...
      - name: Install goveralls
        run: go install github.com/mattn/goveralls@latest
      - name: Send coverage
        env:
          COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          goveralls -coverprofile=profile.cov -service=github
